export const maiddetails = [
    {
        id: 1,
        name: "Sunita Devi",
        age: 32,
        experience: "5 Years",
        city: "Ahmedabad",
        address: "Gota, Shilp Residency",
        service: "House Cleaning",
        salary: 300,
        rating: 4.6,
        photo: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e"
    },
    {
        id: 2,
        name: "Rekha Sharma",
        age: 28,
        experience: "3 Years",
        city: "Ahmedabad",
        address: "Satellite,Anandnagar Society",
        service: "Cooking Maid",
        salary: 280,
        rating: 4.4,
        photo: "https://images.unsplash.com/photo-1544005313-94ddf0286df2"
    },
    {
        id: 3,
        name: "Pooja Patel",
        age: 35,
        experience: "6 Years",
        city: "Ahmedabad",
        address: "Bopal, Aaryan Residency",
        service: "Babysitter",
        salary: 350,
        rating: 4.8,
        photo: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d"
    },
    {
        id: 4,
        name: "Kavita Ben",
        age: 30,
        experience: "4 Years",
        city: "Ahmedabad",
        address: "Prahlad Nagar, Titanium City",
        service: "Elder Care",
        salary: 270,
        rating: 4.5,
        photo: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1"
    },
    {
        id: 5,
        name: "Anita Kumari",
        age: 38,
        experience: "7 Years",
        city: "Ahmedabad",
        address: "Vastrapur, Sun City   .",
        service: "Full Time",
        salary: 400,
        rating: 4.9,
        photo: "https://images.unsplash.com/photo-1488426862026-3ee34a7d66df"
    },

    {
        id: 6,
        name: "Meena Bai",
        age: 26,
        experience: "2 Years",
        city: "Ahmedabad",
        address: "Chandkheda, Savvy Swaraj",
        service: "House Cleaning",
        salary: 250,
        rating: 4.1,
        photo: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e"
    },
    {
        id: 7,
        name: "Rani Singh",
        age: 33,
        experience: "5 Years",
        city: "Ahmedabad",
        address: "Naranpura, Shyam Flats",
        service: "Cooking Maid",
        salary: 310,
        rating: 4.6,
        photo: "https://images.unsplash.com/photo-1494790108377-be9c29b29330"
    },
    {
        id: 8,
        name: "Seema Joshi",
        age: 29,
        experience: "3 Years",
        city: "Ahmedabad",
        address: "Paldi, Dev Residency",
        service: "Babysitter",
        salary: 260,
        rating: 4.3,
        photo: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde"
    },
    {
        id: 9,
        name: "Radha Verma",
        age: 36,
        experience: "6 Years",
        city: "Ahmedabad",
        address: "Thaltej, Shreeji Heights",
        service: "Elder Care",
        salary: 340,
        rating: 4.7,
        photo: "https://images.unsplash.com/photo-1520813792240-56fc4a3765a7"
    },
    {
        id: 10,
        name: "Neha Gupta",
        age: 31,
        experience: "4 Years",
        city: "Ahmedabad",
        address: "Science CityAryavart Heights",
        service: "Full Time",
        salary: 290,
        rating: 4.5,
        photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d"
    },

    {
        id: 11,
        name: "Priya Mishra",
        age: 34,
        experience: "5 Years",
        city: "Ahmedabad",
        address: "Motera, Zundal Homes",
        service: "House Cleaning",
        salary: 300,
        rating: 4.6,
        photo: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e"
    },
    {
        id: 12,
        name: "Aarti Rai",
        age: 27,
        experience: "3 Years",
        city: "Ahmedabad",
        address: "Ranip, Krishna Apartments",
        service: "Cooking Maid",
        salary: 250,
        rating: 4.2,
        photo: "https://images.unsplash.com/photo-1544723795-3fb6469f5b39"
    },
    {
        id: 13,
        name: "Komal Jain",
        age: 35,
        experience: "6 Years",
        city: "Ahmedabad",
        address: "Isanpur, Pushpak Society",
        service: "Babysitter",
        salary: 330,
        rating: 4.7,
        photo: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce"
    },
    {
        id: 14,
        name: "Nisha Rawat",
        age: 30,
        experience: "4 Years",
        city: "Ahmedabad",
        address: "Maninagar, Radhe Flats",
        service: "Elder Care",
        salary: 280,
        rating: 4.4,
        photo: "https://images.unsplash.com/photo-1517841905240-472988babdf9"
    },
    {
        id: 15,
        name: "Sarla Yadav",
        age: 40,
        experience: "8 Years",
        city: "Ahmedabad",
        address: "Naroda, Om Residency",
        service: "Full Time",
        salary: 420,
        rating: 4.9,
        photo: "https://images.unsplash.com/photo-1534528741775-53994a69daeb"
    },

    {
        id: 16,
        name: "Babita Kumari",
        age: 28,
        experience: "3 Years",
        city: "Ahmedabad",
        address: "Vejalpur, Akshar Heights",
        service: "House Cleaning",
        salary: 260,
        rating: 4.2,
        photo: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91"
    },
    {
        id: 17,
        name: "Geeta Verma",
        age: 33,
        experience: "5 Years",
        city: "Ahmedabad",
        address: "Jodhpur, Orchid Greens",
        service: "Cooking Maid",
        salary: 300,
        rating: 4.5,
        photo: "https://images.unsplash.com/photo-1488161628813-04466f872be2"
    },
    {
        id: 18,
        name: "Manju Devi",
        age: 29,
        experience: "3 Years",
        city: "Ahmedabad",
        address: "Memnagar, Shanti Tower",
        service: "Babysitter",
        salary: 280,
        rating: 4.3,
        photo: "https://images.unsplash.com/photo-1547425260-76bcadfb4f2c"
    },
    {
        id: 19,
        name: "Suman Yadav",
        age: 37,
        experience: "6 Years",
        city: "Ahmedabad",
        address: "Ellisbridge, Silver Arc",
        service: "Elder Care",
        salary: 350,
        rating: 4.7,
        photo: "https://images.unsplash.com/photo-1499996860823-5214fcc65f8f"
    },
    {
        id: 20,
        name: "Kiran Sharma",
        age: 32,
        experience: "4 Years",
        city: "Ahmedabad",
        address: "Navrangpura,Maple",
        service: "Full Time",
        salary: 310,
        rating: 4.4,
        photo: "https://images.unsplash.com/photo-1531123897727-8f129e1688ce"
    },

    {
        id: 21,
        name: "Shanti Devi",
        age: 34,
        experience: "5 Years",
        city: "Ahmedabad",
        address: "Gurukul, Heritage Homes",
        service: "House Cleaning",
        salary: 290,
        rating: 4.5,
        photo: "https://images.unsplash.com/photo-1502685104226-ee32379fefbe"
    },
    {
        id: 22,
        name: "Kamla Bai",
        age: 29,
        experience: "3 Years",
        city: "Ahmedabad",
        address: "Ambawadi, Blue Bells",
        service: "Cooking Maid",
        salary: 270,
        rating: 4.3,
        photo: "https://images.unsplash.com/photo-1499996860823-5214fcc65f8f"
    },
    {
        id: 23,
        name: "Pinki Yadav",
        age: 31,
        experience: "4 Years",
        city: "Ahmedabad",
        address: "Bodakdev, Venus Atlantis",
        service: "Babysitter",
        salary: 300,
        rating: 4.4,
        photo: "https://images.unsplash.com/photo-1520813792240-56fc4a3765a7"
    },
    {
        id: 24,
        name: "Lata Sharma",
        age: 36,
        experience: "6 Years",
        city: "Ahmedabad",
        address: "Shahibaug, Green Valley",
        service: "Elder Care",
        salary: 340,
        rating: 4.7,
        photo: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde"
    },
    {
        id: 25,
        name: "Rupa Patel",
        age: 39,
        experience: "7 Years",
        city: "Ahmedabad",
        address: "Kankaria, Lake View Flats",
        service: "Full Time",
        salary: 410,
        rating: 4.9,
        photo: "https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e"
    },

    {
        id: 26,
        name: "Savitri",
        age: 27,
        experience: "2 Years",
        city: "Ahmedabad",
        address: "CTM, Royal Enclave",
        service: "House Cleaning",
        salary: 240,
        rating: 4.1,
        photo: "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91"
    },
    {
        id: 27,
        name: "Nirmala",
        age: 33,
        experience: "5 Years",
        city: "Ahmedabad",
        address: "Hatkeshwar, Shivalik Homes",
        service: "Cooking Maid",
        salary: 310,
        rating: 4.6,
        photo: "https://images.unsplash.com/photo-1488161628813-04466f872be2"
    },
    {
        id: 28,
        name: "Payal",
        age: 28,
        experience: "3 Years",
        city: "Ahmedabad",
        address: "Nikol, Shree Ram Residency",
        service: "Babysitter",
        salary: 260,
        rating: 4.3,
        photo: "https://images.unsplash.com/photo-1547425260-76bcadfb4f2c"
    },
    {
        id: 29,
        name: "Usha",
        age: 37,
        experience: "6 Years",
        city: "Ahmedabad",
        address: "Odhav, Umiya Park     .",
        service: "Elder Care",
        salary: 350,
        rating: 4.7,
        photo: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce"
    },
    {
        id: 30,
        name: "Reena",
        age: 32,
        experience: "4 Years",
        city: "Ahmedabad",
        address: "Aslali, Green Pearl",
        service: "Full Time",
        salary: 320,
        rating: 4.5,
        photo: "https://images.unsplash.com/photo-1531123897727-8f129e1688ce"
    },

    {
        id: 31,
        name: "Mala",
        age: 35,
        experience: "5 Years",
        city: "Ahmedabad",
        address: "Sanand, Orchid Residency",
        service: "House Cleaning",
        salary: 300,
        rating: 4.6,
        photo: "https://images.unsplash.com/photo-1544005313-94ddf0286df2"
    },
    {
        id: 32,
        name: "Sarla",
        age: 29,
        experience: "3 Years",
        city: "Ahmedabad",
        address: "Shela, Signature Homes",
        service: "Cooking Maid",
        salary: 270,
        rating: 4.3,
        photo: "https://images.unsplash.com/photo-1517841905240-472988babdf9"
    },
    {
        id: 33,
        name: "Kanchan",
        age: 31,
        experience: "4 Years",
        city: "Ahmedabad",
        address: "South Bopal, Aryan Square",
        service: "Babysitter",
        salary: 290,
        rating: 4.4,
        photo: "https://images.unsplash.com/photo-1544723795-3fb6469f5b39"
    },
    {
        id: 34,
        name: "Ganga",
        age: 38,
        experience: "7 Years",
        city: "Ahmedabad",
        address: "Ghuma, Harmony Heights",
        service: "Elder Care",
        salary: 360,
        rating: 4.8,
        photo: "https://images.unsplash.com/photo-1534528741775-53994a69daeb"
    },
    {
        id: 35,
        name: "Suman",
        age: 34,
        experience: "5 Years",
        city: "Ahmedabad",
        address: "Sola, Platinum Residency",
        service: "Full Time",
        salary: 330,
        rating: 4.6,
        photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d"
    },

    {
        id: 36,
        name: "Rukmini",
        age: 26,
        experience: "2 Years",
        city: "Ahmedabad",
        address: "Chharodi, Elite Palace",
        service: "House Cleaning",
        salary: 240,
        rating: 4.0,
        photo: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e"
    },
    {
        id: 37,
        name: "Champa",
        age: 33,
        experience: "5 Years",
        city: "Ahmedabad",
        address: "Hebatpur, Sky City   .  .",
        service: "Cooking Maid",
        salary: 300,
        rating: 4.5,
        photo: "https://images.unsplash.com/photo-1494790108377-be9c29b29330"
    },
    {
        id: 38,
        name: "Rakhi",
        age: 28,
        experience: "3 Years",
        city: "Ahmedabad",
        address: "Tragad, Sunrise Homes",
        service: "Babysitter",
        salary: 270,
        rating: 4.2,
        photo: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1"
    },
    {
        id: 39,
        name: "Pushpa",
        age: 37,
        experience: "6 Years",
        city: "Ahmedabad",
        address: "Bareja, Nilkanth Society",
        service: "Elder Care",
        salary: 350,
        rating: 4.7,
        photo: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce"
    },
    {
        id: 40,
        name: "Bhavna",
        age: 35,
        experience: "5 Years",
        city: "Ahmedabad",
        address: "Vinzol, Radha Krishna Flats",
        service: "Full Time",
        salary: 340,
        rating: 4.6,
        photo: "https://images.unsplash.com/photo-1502685104226-ee32379fefbe"
    }
];
